// DEMO ONLY — these are static seed objects for UI development.
// Replace with real data from app/actions/artifacts.ts before production.
// IDs follow the pattern xeref-art-NNN for easy tracing in logs.

import type { Artifact } from '@/lib/types'

export const MOCK_ARTIFACTS: Artifact[] = [
  {
    id: 'xeref-art-001',
    title: 'OpenRouter Chat Proxy',
    description: 'Server-side proxy that routes chat requests to OpenRouter with plan-aware model resolution.',
    type: 'code',
    status: 'published',
    capabilities: ['ai-powered'],
    language: 'typescript',
    versions: [
      {
        version: 1,
        label: 'Initial skeleton',
        language: 'typescript',
        createdAt: '2026-03-10T09:00:00Z',
        content: `// OpenRouter Chat Proxy — v1\nimport { OpenAI } from 'openai'\n\nexport async function routeChat(model: string, messages: unknown[]) {\n  // TODO: add plan check\n  const client = new OpenAI({ baseURL: 'https://openrouter.ai/api/v1' })\n  return client.chat.completions.create({ model, messages: messages as never })\n}`,
      },
      {
        version: 2,
        label: 'Added error handling',
        language: 'typescript',
        createdAt: '2026-03-18T14:22:00Z',
        content: `// OpenRouter Chat Proxy — v2\nimport { OpenAI } from 'openai'\n\nconst PLAN_MODELS: Record<string, string[]> = {\n  free: ['xeref-free'],\n  pro: ['xeref-free', 'claude-haiku-4-5-20251001', 'claude-sonnet-4-6'],\n  ultra: ['*'],\n}\n\nexport async function routeChat(model: string, messages: unknown[], plan: string) {\n  const allowed = PLAN_MODELS[plan] ?? PLAN_MODELS.free\n  if (!allowed.includes('*') && !allowed.includes(model)) {\n    throw new Error('PLAN_LIMIT')\n  }\n  const client = new OpenAI({ baseURL: 'https://openrouter.ai/api/v1' })\n  return client.chat.completions.create({ model, messages: messages as never })\n}`,
      },
      {
        version: 3,
        label: 'Stable v3',
        language: 'typescript',
        createdAt: '2026-04-01T11:00:00Z',
        content: `// OpenRouter Chat Proxy — v3 (production)\nimport { OpenAI } from 'openai'\n\ntype UserPlan = 'free' | 'pro' | 'ultra'\n\nconst PLAN_MODELS: Record<UserPlan, string[]> = {\n  free: ['xeref-free'],\n  pro: ['xeref-free', 'claude-haiku-4-5-20251001', 'claude-sonnet-4-6'],\n  ultra: ['xeref-free', 'claude-haiku-4-5-20251001', 'claude-sonnet-4-6', 'claude-opus-4-6', 'best'],\n}\n\nexport async function routeChat(\n  model: string,\n  messages: Array<{ role: string; content: string }>,\n  plan: UserPlan,\n  apiKey: string,\n) {\n  if (!PLAN_MODELS[plan].includes(model)) {\n    return { error: 'PLAN_LIMIT', status: 403 }\n  }\n  const client = new OpenAI({ baseURL: 'https://openrouter.ai/api/v1', apiKey })\n  return client.chat.completions.create({ model, messages, stream: true })\n}`,
      },
    ],
    currentVersion: 2,
    published: true,
    shareUrl: 'https://xeref.ai/artifacts/my?id=xeref-art-001',
    tags: ['openrouter', 'proxy', 'ai'],
    createdAt: '2026-03-10T09:00:00Z',
    updatedAt: '2026-04-01T11:00:00Z',
  },

  {
    id: 'xeref-art-002',
    title: 'Daily Summary Workflow',
    description: 'Fetches task completions and sends a daily digest via MCP notification channel.',
    type: 'workflow',
    status: 'error',
    capabilities: ['mcp-enabled'],
    versions: [
      {
        version: 1,
        label: 'Initial draft',
        createdAt: '2026-04-10T08:00:00Z',
        content: `trigger: scheduled_daily\nschedule: "0 9 * * *"\n\nsteps:\n  - name: fetch_completed_tasks\n    action: query_supabase\n    table: tasks\n    filter: "status = 'done' AND updated_at > now() - interval '24 hours'"\n\n  - name: summarize\n    action: run_agent\n    prompt: "Summarize these completed tasks: {{fetch_completed_tasks.results}}"\n\n  - name: send_digest\n    action: mcp_notify\n    channel: "@user"\n    message: "{{summarize.output}}"`,
      },
    ],
    currentVersion: 0,
    published: false,
    tags: ['mcp', 'workflow', 'daily'],
    createdAt: '2026-04-10T08:00:00Z',
    updatedAt: '2026-04-17T09:14:00Z',
  },

  {
    id: 'xeref-art-003',
    title: 'Agent System Prompt',
    description: 'Reusable system prompt template for Xeref productivity agents with MCP tool access.',
    type: 'prompt',
    status: 'draft',
    capabilities: ['mcp-enabled', 'ai-powered'],
    language: 'markdown',
    versions: [
      {
        version: 1,
        label: 'Draft v1',
        language: 'markdown',
        createdAt: '2026-04-15T10:00:00Z',
        content: `# Xeref Agent System Prompt\n\nYou are a productivity assistant built on xeref.ai. You have access to the following tools via MCP:\n\n- **tasks**: Create, update, and query tasks\n- **calendar**: Read and create calendar events\n- **memory**: Store and retrieve user preferences\n- **notifications**: Send alerts and reminders\n\n## Behavior Guidelines\n\n- Always confirm before deleting or modifying existing data\n- Prefer concise responses unless the user asks for detail\n- When unsure, ask a clarifying question rather than guessing\n- Use markdown formatting for structured output\n\n## Tone\n\nProfessional, helpful, and direct. Never sycophantic.`,
      },
    ],
    currentVersion: 0,
    published: false,
    tags: ['prompt', 'mcp', 'system'],
    createdAt: '2026-04-15T10:00:00Z',
    updatedAt: '2026-04-16T11:30:00Z',
  },

  {
    id: 'xeref-art-004',
    title: 'Embeddings Pipeline',
    description: 'Python script that chunks documents, generates embeddings via AI, and stores them in vector storage.',
    type: 'code',
    status: 'processing',
    capabilities: ['ai-powered', 'storage-enabled'],
    language: 'python',
    versions: [
      {
        version: 1,
        label: 'Generating…',
        language: 'python',
        createdAt: '2026-04-18T08:00:00Z',
        content: `# Embeddings Pipeline\n# Status: AI is generating this artifact...\n\nimport anthropic\nfrom supabase import create_client\n\n# TODO: complete implementation`,
      },
    ],
    currentVersion: 0,
    published: false,
    tags: ['embeddings', 'python', 'vector'],
    createdAt: '2026-04-18T08:00:00Z',
    updatedAt: '2026-04-18T08:01:00Z',
  },

  {
    id: 'xeref-art-005',
    title: 'API Integration Guide',
    description: 'Step-by-step guide for integrating xeref.ai APIs into third-party applications.',
    type: 'document',
    status: 'published',
    capabilities: ['storage-enabled'],
    language: 'markdown',
    versions: [
      {
        version: 1,
        label: 'Draft',
        language: 'markdown',
        createdAt: '2026-04-05T09:00:00Z',
        content: `# API Integration Guide\n\nThis guide covers integrating xeref.ai into your application.\n\n## Prerequisites\n\n- Node.js 18+\n- A xeref.ai Pro or Ultra account\n- API key from your dashboard\n\n## Quick Start\n\n\`npm install @xeref/sdk\`\n\n## First Request\n\nSend your first message to the chat endpoint.`,
      },
      {
        version: 2,
        label: 'Final',
        language: 'markdown',
        createdAt: '2026-04-12T14:00:00Z',
        content: `# API Integration Guide\n\nThis guide covers integrating xeref.ai into your application with full examples.\n\n## Prerequisites\n\n- Node.js 18+\n- A xeref.ai Pro or Ultra account\n- API key from Settings → API Keys\n\n## Installation\n\n\`npm install @xeref/sdk\`\n\n## Authentication\n\nAll requests require a Bearer token in the Authorization header.\n\n## Endpoints\n\n- **POST /api/chat** — Stream a chat completion\n- **GET /api/projects** — List saved projects\n- **POST /api/artifacts** — Create a new artifact\n\n## Rate Limits\n\n| Plan | Requests/min |\n|------|--------------|\n| Pro  | 60           |\n| Ultra| 300          |\n\n## Support\n\nContact support@xeref.ai for enterprise integrations.`,
      },
    ],
    currentVersion: 1,
    published: true,
    shareUrl: 'https://xeref.ai/artifacts/my?id=xeref-art-005',
    tags: ['docs', 'api', 'integration'],
    createdAt: '2026-04-05T09:00:00Z',
    updatedAt: '2026-04-12T14:00:00Z',
  },

  {
    id: 'xeref-art-006',
    title: 'Dashboard UI Concept',
    description: 'AI-generated UI mockup for a future dashboard redesign concept.',
    type: 'image',
    status: 'published',
    capabilities: ['ai-powered'],
    imageUrl: 'https://placehold.co/800x500/1a1a2e/22d3ee?text=AI+Generated+Mockup',
    versions: [
      {
        version: 1,
        label: 'Generated',
        createdAt: '2026-04-14T16:00:00Z',
        content: 'https://placehold.co/800x500/1a1a2e/22d3ee?text=AI+Generated+Mockup',
      },
    ],
    currentVersion: 0,
    published: true,
    shareUrl: 'https://xeref.ai/artifacts/my?id=xeref-art-006',
    tags: ['ui', 'design', 'ai-generated'],
    createdAt: '2026-04-14T16:00:00Z',
    updatedAt: '2026-04-14T16:00:00Z',
  },

  {
    id: 'xeref-art-007',
    title: 'Feature Usage Export',
    description: 'JSON export of CLAWS feature selection analytics, ready for BI tools.',
    type: 'data',
    status: 'published',
    capabilities: ['mcp-enabled', 'storage-enabled'],
    language: 'json',
    versions: [
      {
        version: 1,
        label: 'April export',
        language: 'json',
        createdAt: '2026-04-18T00:00:00Z',
        content: `{\n  "exported_at": "2026-04-18T00:00:00Z",\n  "period": "2026-04",\n  "records": [\n    { "feature_id": "connect-001", "name": "Email Integration", "selections": 142 },\n    { "feature_id": "listen-003", "name": "Webhook Listener", "selections": 98 },\n    { "feature_id": "archive-007", "name": "File Storage", "selections": 87 },\n    { "feature_id": "wire-002", "name": "API Bridge", "selections": 76 },\n    { "feature_id": "sense-004", "name": "Sentiment Analysis", "selections": 65 },\n    { "feature_id": "agent-001", "name": "Task Automation", "selections": 201 }\n  ],\n  "total_selections": 669,\n  "unique_users": 43\n}`,
      },
    ],
    currentVersion: 0,
    published: true,
    shareUrl: 'https://xeref.ai/artifacts/my?id=xeref-art-007',
    tags: ['analytics', 'export', 'json'],
    createdAt: '2026-04-18T00:00:00Z',
    updatedAt: '2026-04-18T00:00:00Z',
  },

  {
    id: 'xeref-art-008',
    title: 'Deploy Script',
    description: 'Bash deployment script for xeref.ai production with environment variable injection and structured logging.',
    type: 'code',
    status: 'draft',
    capabilities: [],
    language: 'bash',
    versions: [
      {
        version: 1,
        label: 'Initial script',
        language: 'bash',
        createdAt: '2026-04-01T09:00:00Z',
        content: `#!/bin/bash\n# Deploy script v1\necho "Deploying..."\nvercel deploy`,
      },
      {
        version: 2,
        label: 'Parameterized',
        language: 'bash',
        createdAt: '2026-04-08T11:00:00Z',
        content: `#!/bin/bash\n# Deploy script v2\nset -e\nENV=\${1:-"production"}\necho "Deploying to $ENV..."\nvercel deploy --env $ENV`,
      },
      {
        version: 3,
        label: 'With logging',
        language: 'bash',
        createdAt: '2026-04-14T15:00:00Z',
        content: `#!/bin/bash\n# Deploy script v3\nset -e\nENV=\${1:-"production"}\nLOG_FILE="deploy_$(date +%Y%m%d_%H%M%S).log"\necho "Deploying to $ENV... (log: $LOG_FILE)"\nvercel deploy --env $ENV 2>&1 | tee $LOG_FILE\necho "Done. Exit code: $?"`,
      },
      {
        version: 4,
        label: 'Production ready',
        language: 'bash',
        createdAt: '2026-04-18T07:00:00Z',
        content: `#!/bin/bash\n# Deploy script v4 — production ready\nset -euo pipefail\n\nENV="\${1:-production}"\nPROJECT="\${2:-xeref}"\nLOG_DIR="./logs/deploys"\nLOG_FILE="$LOG_DIR/deploy_\${ENV}_$(date +%Y%m%d_%H%M%S).log"\n\nmkdir -p "$LOG_DIR"\n\necho "[$(date)] Starting $PROJECT deploy to $ENV" | tee -a "$LOG_FILE"\n\n# Pre-deploy checks\nnpm run build 2>&1 | tee -a "$LOG_FILE"\nnpm run lint  2>&1 | tee -a "$LOG_FILE"\n\n# Deploy\nvercel deploy --prod 2>&1 | tee -a "$LOG_FILE"\n\necho "[$(date)] Deploy complete" | tee -a "$LOG_FILE"`,
      },
    ],
    currentVersion: 3,
    published: false,
    tags: ['bash', 'deploy', 'devops'],
    createdAt: '2026-04-01T09:00:00Z',
    updatedAt: '2026-04-18T07:00:00Z',
  },
]
