import { BarChart2, CalendarDays, CheckSquare, GitFork, Inbox, Clock } from 'lucide-react'
import { Badge } from '@/components/ui/badge'

interface ComingSoonViewProps {
  viewName: string
}

const VIEW_META: Record<string, { icon: React.ElementType; description: string }> = {
  'Stats': {
    icon: BarChart2,
    description: 'Track your agent usage, prompt generation frequency, and feature adoption over time.',
  },
  'Calendar': {
    icon: CalendarDays,
    description: 'Schedule and review agent runs, deadlines, and deployment events.',
  },
  'Workflows': {
    icon: GitFork,
    description: 'Chain agents together into automated multi-step workflows.',
  },
  'Inbox': {
    icon: Inbox,
    description: 'Receive notifications and outputs from your running agents.',
  },
  'All Tasks': {
    icon: CheckSquare,
    description: 'Review all tasks assigned to or generated by your agents.',
  },
}

export function ComingSoonView({ viewName }: ComingSoonViewProps) {
  const meta = VIEW_META[viewName]
  const Icon = meta?.icon ?? Clock

  return (
    <section
      aria-label={viewName}
      className="flex flex-1 flex-col items-center justify-center text-center p-8"
    >
      <div className="rounded-full bg-primary/10 p-5 mb-5">
        <Icon className="h-8 w-8 text-primary" />
      </div>
      <h1 className="text-xl font-semibold mb-2">{viewName}</h1>
      <Badge variant="secondary" className="mb-3">Coming Soon</Badge>
      {meta?.description && (
        <p className="text-sm text-muted-foreground max-w-xs mb-4">{meta.description}</p>
      )}
      <p className="text-xs text-muted-foreground/60">
        Want this sooner?{' '}
        <a
          href="mailto:hi@xeref.ai"
          className="underline underline-offset-2 hover:text-foreground transition-colors"
        >
          Let us know
        </a>
      </p>
    </section>
  )
}
