import {
  Github,
  Mail,
  Calendar,
  FileText,
  MessageSquare,
  Database,
  Search,
  Globe,
} from 'lucide-react'
import type { Connector } from './types'

export const AVAILABLE_CONNECTORS: Connector[] = [
  {
    id: 'github',
    name: 'GitHub',
    service: 'github',
    icon: Github,
    color: 'text-foreground',
    connected: false,
    description: 'Access repos, issues, and pull requests.',
    scopes: ['repo', 'read:user'],
  },
  {
    id: 'gmail',
    name: 'Gmail',
    service: 'google',
    icon: Mail,
    color: 'text-red-400',
    connected: false,
    description: 'Read and send emails on your behalf.',
    scopes: ['gmail.readonly', 'gmail.send'],
  },
  {
    id: 'gcal',
    name: 'Google Calendar',
    service: 'google',
    icon: Calendar,
    color: 'text-blue-400',
    connected: false,
    description: 'View and create calendar events.',
    scopes: ['calendar.events'],
  },
  {
    id: 'notion',
    name: 'Notion',
    service: 'notion',
    icon: FileText,
    color: 'text-foreground',
    connected: false,
    description: 'Read and write Notion pages and databases.',
  },
  {
    id: 'slack',
    name: 'Slack',
    service: 'slack',
    icon: MessageSquare,
    color: 'text-purple-400',
    connected: false,
    description: 'Send messages and read channels.',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    service: 'supabase',
    icon: Database,
    color: 'text-green-400',
    connected: false,
    description: 'Query your Supabase database tables.',
  },
  {
    id: 'websearch',
    name: 'Web Search',
    service: 'internal',
    icon: Search,
    color: 'text-yellow-400',
    connected: true,
    description: 'Let agents search the web in real time.',
  },
  {
    id: 'webhook',
    name: 'Custom Webhook',
    service: 'custom',
    icon: Globe,
    color: 'text-cyan-400',
    connected: false,
    description: 'Call any HTTP endpoint from your agents.',
  },
]

export const TOOL_OPTIONS = [
  'web_search',
  'read_file',
  'write_file',
  'run_code',
  'send_email',
  'query_db',
]
