import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowLeft, BookOpen } from 'lucide-react';
import { XerefLogo } from '@/components/xeref-logo';

export default function TermsPage() {
  return (
    <div className="container mx-auto max-w-4xl py-12 px-4">
      <div className="mb-8">
        <Button variant="ghost" className="pl-0 gap-2 mb-4 hover:bg-transparent" asChild>
          <Link href="/">
            <ArrowLeft size={16} /> <XerefLogo className="h-6 w-6 ml-1" /> <span className="font-bold">xeref.ai</span>
          </Link>
        </Button>
        <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl mb-4 flex items-center gap-3">
          <BookOpen className="text-primary w-10 h-10" /> Terms of Service
        </h1>
        <p className="text-xl text-muted-foreground">
          Your rights and responsibilities when using xeref.ai 
        </p>
      </div>

      <div className="prose dark:prose-invert max-w-none space-y-8">
        <section>
          <h2 className="text-2xl font-bold border-b pb-2">1. Usage</h2>
          <p className="leading-7 mt-4">
            By using <strong>xeref.ai</strong> (and the Xeref-Claw tool), you agree to use our platform responsibly. We provide a tool that generates prompts and implementation plans for AI agents. You are responsible for the code generated via those prompts.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold border-b pb-2">2. Liability</h2>
          <p className="leading-7 mt-4">
            The service is provided &quot;as is&quot;. We do not guarantee that the generated prompts will always be 100% accurate or up-to-date with current AI models. You should review all code generated by an AI before deployment.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold border-b pb-2">3. Intellectual Property</h2>
          <p className="leading-7 mt-4">
            The Xeref-Claw tool and brand are the property of <strong>xeref.ai</strong>. You are free to use the generated prompts for your own projects, both personal and commercial.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold border-b pb-2">4. Prohibited Acts</h2>
          <p className="leading-7 mt-4">
             Please do not use our tool to generate harmful agents, malicious code, or use it in ways that violate others&apos; privacy. Use AI for good!
          </p>
        </section>

        <footer className="mt-12 pt-8 border-t text-sm text-muted-foreground italic">
          Last updated: March 20, 2026
        </footer>
      </div>
    </div>
  );
}
