import type { DesignProject } from "@/types/design";

export const EXAMPLE_PROJECTS: DesignProject[] = [
  {
    id: "example-1",
    org_id: "example",
    owner_id: "example",
    name: "Brand Refresh — High Fidelity",
    project_type: "prototype",
    prototype_mode: "high_fidelity",
    use_speaker_notes: false,
    template_id: null,
    design_system_id: null,
    visibility: "org",
    status: "active",
    thumbnail_url: null,
    meta: {},
    created_at: "2026-04-01T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
  },
  {
    id: "example-2",
    org_id: "example",
    owner_id: "example",
    name: "Q2 Product Roadmap",
    project_type: "slide_deck",
    prototype_mode: null,
    use_speaker_notes: true,
    template_id: null,
    design_system_id: null,
    visibility: "org",
    status: "active",
    thumbnail_url: null,
    meta: {},
    created_at: "2026-03-15T00:00:00Z",
    updated_at: "2026-03-15T00:00:00Z",
  },
  {
    id: "example-3",
    org_id: "example",
    owner_id: "example",
    name: "Mobile App Wireframes",
    project_type: "prototype",
    prototype_mode: "wireframe",
    use_speaker_notes: false,
    template_id: null,
    design_system_id: null,
    visibility: "org",
    status: "active",
    thumbnail_url: null,
    meta: {},
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "example-4",
    org_id: "example",
    owner_id: "example",
    name: "Sales Pitch Template",
    project_type: "template",
    prototype_mode: null,
    use_speaker_notes: false,
    template_id: null,
    design_system_id: null,
    visibility: "org",
    status: "active",
    thumbnail_url: null,
    meta: {},
    created_at: "2026-02-20T00:00:00Z",
    updated_at: "2026-02-20T00:00:00Z",
  },
  {
    id: "example-5",
    org_id: "example",
    owner_id: "example",
    name: "User Research Synthesis",
    project_type: "other",
    prototype_mode: null,
    use_speaker_notes: false,
    template_id: null,
    design_system_id: null,
    visibility: "org",
    status: "active",
    thumbnail_url: null,
    meta: {},
    created_at: "2026-02-10T00:00:00Z",
    updated_at: "2026-02-10T00:00:00Z",
  },
  {
    id: "example-6",
    org_id: "example",
    owner_id: "example",
    name: "Onboarding Flow — High Fidelity",
    project_type: "prototype",
    prototype_mode: "high_fidelity",
    use_speaker_notes: false,
    template_id: null,
    design_system_id: null,
    visibility: "org",
    status: "active",
    thumbnail_url: null,
    meta: {},
    created_at: "2026-01-25T00:00:00Z",
    updated_at: "2026-01-25T00:00:00Z",
  },
];
